jooq: # do not use internal property link(e.g., ${spring.application.name})
  generator:
    directory: src/generated
    datasource:
      url:
      schema: entasdfsdb
      username:
      password:

logging:
  level:
    org.jooq:
      Constants: off
      tools:
        LoggerListener: info
