## Common Profile
spring:
  cloud:
    aws:
      credentials:
        access-key:
        secret-key:
      region:
        static: ap-northeast-2
      s3:
        bucket:



---
## PRD Profile
spring:
  config.activate.on-profile: prd



---
## DEV Profile
spring:
  config.activate.on-profile: dev



---
## LOCAL Profile
spring:
  config.activate.on-profile: local
