## Common Profile



---
## PRD Profile
spring:
  config.activate.on-profile: prd



---
## DEV Profile
spring:
  config.activate.on-profile: dev



---
## LOCAL Profile
spring:
  config.activate.on-profile: local
