INSERT INTO common_code (code_key, upper_key, depth, display_order, use_yn, code_id, code_desc) VALUES (0, 0, 0, 0, 'N', '', '');
INSERT INTO common_code (code_key, upper_key, depth, display_order, use_yn, code_id, code_desc) VALUES (1, 0, 1, 1, 'Y', 'ORDER', '주문');
INSERT INTO common_code (code_key, upper_key, depth, display_order, use_yn, code_id, code_desc) VALUES (2, 0, 1, 2, 'Y', 'PRODUCT', '상품');
INSERT INTO common_code (code_key, upper_key, depth, display_order, use_yn, code_id, code_desc) VALUES (3, 0, 1, 3, 'Y', 'MEMBER', '회원');
INSERT INTO common_code (code_key, upper_key, depth, display_order, use_yn, code_id, code_desc) VALUES (4, 1, 2, 1, 'Y', 'PAYMENT', '결제');
INSERT INTO common_code (code_key, upper_key, depth, display_order, use_yn, code_id, code_desc) VALUES (5, 4, 3, 1, 'Y', 'PAYMENT_STATUS', '결제상태');
INSERT INTO common_code (code_key, upper_key, depth, display_order, use_yn, code_id, code_desc) VALUES (6, 5, 4, 1, 'Y', 'PURCMP', '결제완료');
INSERT INTO common_code (code_key, upper_key, depth, display_order, use_yn, code_id, code_desc) VALUES (7, 5, 4, 2, 'Y', 'PURCAN', '결제취소');
INSERT INTO common_code (code_key, upper_key, depth, display_order, use_yn, code_id, code_desc) VALUES (8, 4, 3, 2, 'Y', 'PAYMENT_METHOD', '결제수단');
INSERT INTO common_code (code_key, upper_key, depth, display_order, use_yn, code_id, code_desc) VALUES (9, 8, 4, 1, 'Y', 'PAYMENT_METHOD', '일반결제수단');
INSERT INTO common_code (code_key, upper_key, depth, display_order, use_yn, code_id, code_desc) VALUES (10, 9, 5, 1, 'Y', 'REWARD', '적립금');
INSERT INTO common_code (code_key, upper_key, depth, display_order, use_yn, code_id, code_desc) VALUES (11, 8, 4, 2, 'Y', 'PG_PAYMENT_METHOD', 'PG결제수단');
INSERT INTO common_code (code_key, upper_key, depth, display_order, use_yn, code_id, code_desc) VALUES (12, 11, 5, 1, 'Y', 'CREDIT_CARD', '신용카드');
INSERT INTO common_code (code_key, upper_key, depth, display_order, use_yn, code_id, code_desc) VALUES (13, 11, 5, 2, 'Y', 'NAVER_PAY', '네이버페이');
INSERT INTO common_code (code_key, upper_key, depth, display_order, use_yn, code_id, code_desc) VALUES (14, 1, 2, 2, 'Y', 'DELIVERY', '배송');
INSERT INTO common_code (code_key, upper_key, depth, display_order, use_yn, code_id, code_desc) VALUES (15, 14, 3, 1, 'Y', 'DELIVERY_STATUS', '배송상태');
INSERT INTO common_code (code_key, upper_key, depth, display_order, use_yn, code_id, code_desc) VALUES (16, 15, 4, 1, 'Y', 'DELIVERING', '배송중');
INSERT INTO common_code (code_key, upper_key, depth, display_order, use_yn, code_id, code_desc) VALUES (17, 1, 2, 3, 'Y', 'CLAIM', '클레임');
INSERT INTO common_code (code_key, upper_key, depth, display_order, use_yn, code_id, code_desc) VALUES (18, 17, 3, 1, 'Y', 'CLAIM_STATUS', '클레임상태');
INSERT INTO common_code (code_key, upper_key, depth, display_order, use_yn, code_id, code_desc) VALUES (19, 18, 4, 1, 'Y', 'REFUND', '환불');
INSERT INTO common_code (code_key, upper_key, depth, display_order, use_yn, code_id, code_desc) VALUES (20, 0, 1, 4, 'Y', 'MULTILINGUAL', '다국어');
INSERT INTO common_code (code_key, upper_key, depth, display_order, use_yn, code_id, code_desc) VALUES (21, 20, 2, 1, 'Y', 'TARGET', '대상구분');
INSERT INTO common_code (code_key, upper_key, depth, display_order, use_yn, code_id, code_desc) VALUES (22, 21, 3, 1, 'Y', 'COMMON_CODE', '공통코드');
INSERT INTO common_code (code_key, upper_key, depth, display_order, use_yn, code_id, code_desc) VALUES (23, 21, 3, 2, 'Y', 'PRODUCT', '상품');
INSERT INTO common_code (code_key, upper_key, depth, display_order, use_yn, code_id, code_desc) VALUES (24, 21, 3, 3, 'Y', 'STANDARD_CATEGORY', '표준 카테고리');
INSERT INTO common_code (code_key, upper_key, depth, display_order, use_yn, code_id, code_desc) VALUES (25, 21, 3, 4, 'Y', 'DISPLAY_CATEGORY', '전시 카테고리');
INSERT INTO common_code (code_key, upper_key, depth, display_order, use_yn, code_id, code_desc) VALUES (26, 21, 3, 5, 'Y', 'BRAND', '브랜드');
INSERT INTO common_code (code_key, upper_key, depth, display_order, use_yn, code_id, code_desc) VALUES (27, 21, 3, 6, 'Y', 'STORE', '매장');
INSERT INTO common_code (code_key, upper_key, depth, display_order, use_yn, code_id, code_desc) VALUES (28, 20, 2, 2, 'Y', 'DESCRIPTION', '설명구분');
INSERT INTO common_code (code_key, upper_key, depth, display_order, use_yn, code_id, code_desc) VALUES (29, 28, 3, 1, 'Y', 'COMMON_CODE', '공통코드');
INSERT INTO common_code (code_key, upper_key, depth, display_order, use_yn, code_id, code_desc) VALUES (30, 29, 4, 1, 'Y', 'CODE_NAME', '코드명');
INSERT INTO common_code (code_key, upper_key, depth, display_order, use_yn, code_id, code_desc) VALUES (31, 28, 3, 2, 'Y', 'PRODUCT', '상품');
INSERT INTO common_code (code_key, upper_key, depth, display_order, use_yn, code_id, code_desc) VALUES (32, 31, 4, 1, 'Y', 'PRODUCT_NAME', '상품명');
INSERT INTO common_code (code_key, upper_key, depth, display_order, use_yn, code_id, code_desc) VALUES (33, 31, 4, 2, 'Y', 'PRODUCT_DESC', '상품설명');
INSERT INTO common_code (code_key, upper_key, depth, display_order, use_yn, code_id, code_desc) VALUES (34, 31, 4, 3, 'Y', 'OPTION_NAME', '옵션명');
INSERT INTO common_code (code_key, upper_key, depth, display_order, use_yn, code_id, code_desc) VALUES (35, 28, 3, 3, 'Y', 'STANDARD_CATEGORY', '표준 카테고리');
INSERT INTO common_code (code_key, upper_key, depth, display_order, use_yn, code_id, code_desc) VALUES (36, 35, 4, 1, 'Y', 'CATEGORY_NAME', '카테고리명');
INSERT INTO common_code (code_key, upper_key, depth, display_order, use_yn, code_id, code_desc) VALUES (37, 28, 3, 4, 'Y', 'DISPLAY_CATEGORY', '전시 카테고리');
INSERT INTO common_code (code_key, upper_key, depth, display_order, use_yn, code_id, code_desc) VALUES (38, 37, 4, 1, 'Y', 'CATEGORY_NAME', '카테고리명');
INSERT INTO common_code (code_key, upper_key, depth, display_order, use_yn, code_id, code_desc) VALUES (39, 28, 3, 5, 'Y', 'BRAND', '브랜드');
INSERT INTO common_code (code_key, upper_key, depth, display_order, use_yn, code_id, code_desc) VALUES (40, 39, 4, 1, 'Y', 'BRAND_NAME', '브랜드명');
INSERT INTO common_code (code_key, upper_key, depth, display_order, use_yn, code_id, code_desc) VALUES (41, 39, 4, 2, 'Y', 'BRAND_DESC', '브랜드 설명');
INSERT INTO common_code (code_key, upper_key, depth, display_order, use_yn, code_id, code_desc) VALUES (42, 28, 3, 6, 'Y', 'PRODUCT', '매장');
INSERT INTO common_code (code_key, upper_key, depth, display_order, use_yn, code_id, code_desc) VALUES (43, 42, 4, 1, 'Y', 'PRODUCT_NAME', '매장명');
INSERT INTO common_code (code_key, upper_key, depth, display_order, use_yn, code_id, code_desc) VALUES (44, 42, 4, 2, 'Y', 'PRODUCT_NAME', '매장 설명');
INSERT INTO common_code (code_key, upper_key, depth, display_order, use_yn, code_id, code_desc) VALUES (45, 20, 2, 3, 'Y', 'CONTENTS', '내용구분');
INSERT INTO common_code (code_key, upper_key, depth, display_order, use_yn, code_id, code_desc) VALUES (46, 45, 3, 1, 'Y', 'SHORT', '짧은문구');
INSERT INTO common_code (code_key, upper_key, depth, display_order, use_yn, code_id, code_desc) VALUES (47, 45, 3, 2, 'Y', 'LONG', '긴문구');
