INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (1, 22, 1, 30, 'ko-kr', 46, '주문', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (2, 22, 2, 30, 'ko-kr', 46, '상품', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (3, 22, 3, 30, 'ko-kr', 46, '회원', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (4, 22, 4, 30, 'ko-kr', 46, '결제', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (5, 22, 5, 30, 'ko-kr', 46, '결제상태', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (6, 22, 6, 30, 'ko-kr', 46, '결제완료', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (7, 22, 7, 30, 'ko-kr', 46, '결제취소', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (8, 22, 8, 30, 'ko-kr', 46, '결제수단', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (9, 22, 9, 30, 'ko-kr', 46, '일반결제수단', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (10, 22, 10, 30, 'ko-kr', 46, '적립금', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (11, 22, 11, 30, 'ko-kr', 46, 'PG결제수단', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (12, 22, 12, 30, 'ko-kr', 46, '신용카드', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (13, 22, 13, 30, 'ko-kr', 46, '네이버페이', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (14, 22, 14, 30, 'ko-kr', 46, '배송', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (15, 22, 15, 30, 'ko-kr', 46, '배송상태', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (16, 22, 16, 30, 'ko-kr', 46, '배송중', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (17, 22, 17, 30, 'ko-kr', 46, '클레임', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (18, 22, 18, 30, 'ko-kr', 46, '클레임상태', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (19, 22, 19, 30, 'ko-kr', 46, '환불', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (20, 22, 20, 30, 'ko-kr', 46, '다국어', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (21, 22, 21, 30, 'ko-kr', 46, '대상 구분', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (22, 22, 22, 30, 'ko-kr', 46, '공통코드', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (23, 22, 23, 30, 'ko-kr', 46, '상품', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (24, 22, 24, 30, 'ko-kr', 46, '표준 카테고리', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (25, 22, 25, 30, 'ko-kr', 46, '전시 카테고리', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (26, 22, 26, 30, 'ko-kr', 46, '브랜드', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (27, 22, 27, 30, 'ko-kr', 46, '매장', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (28, 22, 28, 30, 'ko-kr', 46, '설명 구분', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (29, 22, 29, 30, 'ko-kr', 46, '공통 코드', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (30, 22, 30, 30, 'ko-kr', 46, '코드명', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (31, 22, 31, 30, 'ko-kr', 46, '상품', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (32, 22, 32, 30, 'ko-kr', 46, '상품명', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (33, 22, 33, 30, 'ko-kr', 46, '상품 설명', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (34, 22, 34, 30, 'ko-kr', 46, '옵션명', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (35, 22, 35, 30, 'ko-kr', 46, '표준 카테고리', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (36, 22, 36, 30, 'ko-kr', 46, '카테고리명', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (37, 22, 37, 30, 'ko-kr', 46, '전시 카테고리', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (38, 22, 38, 30, 'ko-kr', 46, '카테고리명', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (39, 22, 39, 30, 'ko-kr', 46, '브랜드', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (40, 22, 40, 30, 'ko-kr', 46, '브랜드명', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (41, 22, 41, 30, 'ko-kr', 46, '브랜드 설명', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (42, 22, 42, 30, 'ko-kr', 46, '매장', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (43, 22, 43, 30, 'ko-kr', 46, '매장명', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (44, 22, 44, 30, 'ko-kr', 46, '매장 설명', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (45, 22, 45, 30, 'ko-kr', 46, '내용 구분', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (46, 22, 46, 30, 'ko-kr', 46, '짧은 문구', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (47, 22, 47, 30, 'ko-kr', 46, '긴 문구', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (48, 22, 1, 30, 'en-us', 46, 'order', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (49, 22, 2, 30, 'en-us', 46, 'product', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (50, 22, 3, 30, 'en-us', 46, 'member', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (51, 22, 4, 30, 'en-us', 46, 'payments', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (52, 22, 5, 30, 'en-us', 46, 'payment status', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (53, 22, 6, 30, 'en-us', 46, 'completed payments', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (54, 22, 7, 30, 'en-us', 46, 'cancelled payments', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (55, 22, 8, 30, 'en-us', 46, 'payment methods', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (56, 22, 9, 30, 'en-us', 46, 'payment methods', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (57, 22, 10, 30, 'en-us', 46, 'rewards', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (58, 22, 11, 30, 'en-us', 46, 'pg payment methods', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (59, 22, 12, 30, 'en-us', 46, 'credit card', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (60, 22, 13, 30, 'en-us', 46, 'naver pay', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (61, 22, 14, 30, 'en-us', 46, 'delivery', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (62, 22, 15, 30, 'en-us', 46, 'delivery status', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (63, 22, 16, 30, 'en-us', 46, 'delivering', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (64, 22, 17, 30, 'en-us', 46, 'claim', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (65, 22, 18, 30, 'en-us', 46, 'claim status', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (66, 22, 19, 30, 'en-us', 46, 'refund', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (67, 22, 20, 30, 'en-us', 46, 'multilingual', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (68, 22, 21, 30, 'en-us', 46, 'targets', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (69, 22, 22, 30, 'en-us', 46, 'common code', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (70, 22, 23, 30, 'en-us', 46, 'product', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (71, 22, 24, 30, 'en-us', 46, 'standard category', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (72, 22, 25, 30, 'en-us', 46, 'display category', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (73, 22, 26, 30, 'en-us', 46, 'brand', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (74, 22, 27, 30, 'en-us', 46, 'store', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (75, 22, 28, 30, 'en-us', 46, 'descriptions', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (76, 22, 29, 30, 'en-us', 46, 'common code', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (77, 22, 30, 30, 'en-us', 46, 'code name', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (78, 22, 31, 30, 'en-us', 46, 'product', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (79, 22, 32, 30, 'en-us', 46, 'product name', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (80, 22, 33, 30, 'en-us', 46, 'product description', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (81, 22, 34, 30, 'en-us', 46, 'option name', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (82, 22, 35, 30, 'en-us', 46, 'standard category', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (83, 22, 36, 30, 'en-us', 46, 'category name', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (84, 22, 37, 30, 'en-us', 46, 'display category', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (85, 22, 38, 30, 'en-us', 46, 'category name', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (86, 22, 39, 30, 'en-us', 46, 'brand', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (87, 22, 40, 30, 'en-us', 46, 'brand name', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (88, 22, 41, 30, 'en-us', 46, 'brand description', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (89, 22, 42, 30, 'en-us', 46, 'store', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (90, 22, 43, 30, 'en-us', 46, 'store name', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (91, 22, 44, 30, 'en-us', 46, 'store description', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (92, 22, 45, 30, 'en-us', 46, 'contents', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (93, 22, 46, 30, 'en-us', 46, 'short contents', null);
INSERT INTO multilingual_desc (desc_key, target_cc_key, target_key, desc_cc_key, lang_cd, cont_cc_key, short_cont, long_cont) VALUES (94, 22, 47, 30, 'en-us', 46, 'long contents', null);
